name: debian-gnuradio

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build-deb10:
    runs-on: ubuntu-latest
    container: debian:10
    steps:
      - name: Config APT sources
        run: echo "deb http://deb.debian.org/debian/ buster main" > /etc/apt/sources.list
      - name: Install build tools
        run: apt-get update && apt-get install -y devscripts build-essential software-properties-common
      - name: Add gnuradio PPA
        run: add-apt-repository --enable-source --yes --keyserver keyserver.ubuntu.com ppa:gnuradio/gnuradio-releases
      - name: Change Ubuntu version
        run: rm /etc/apt/sources.list.d/* && echo "deb-src http://ppa.launchpad.net/gnuradio/gnuradio-releases/ubuntu hirsute main" >> /etc/apt/sources.list
      - name: Install build dependencies
        run: apt-get update && apt-get -y build-dep gnuradio
      - name: build
        run: apt-get source --build gnuradio

